apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ent-est-sale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mehdiechchentili/ent-frontend:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ent-est-sale
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000