apiVersion: v1
kind: ConfigMap
metadata:
  name: ent-config
  namespace: ent-est-sale
data:
  KEYCLOAK_URL: "http://keycloak-service:8080"
  KEYCLOAK_REALM: "ent-est"
  CASSANDRA_HOST: "cassandra-service"
  MINIO_HOST: "minio-service"
  MINIO_PORT: "9000"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "admin"
  OLLAMA_HOST: "ollama-service"
  OLLAMA_PORT: "11434"