apiVersion: v1
kind: Secret
metadata:
  name: ent-secrets
  namespace: ent-est-sale
type: Opaque
stringData:
  RABBITMQ_PASS: "admin123"
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin123"