apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: ent-est-sale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: mehdiechchentili/ent-users-service:latest
          imagePullPolicy: Always   # ✅ IMPORTANT (force pull Docker Hub)
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: ent-config
            - secretRef:
                name: ent-secrets
          readinessProbe:
            httpGet:
              path: /users/health
              port: 8001
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /users/health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: ent-est-sale
spec:
  selector:
    app: users-service
  ports:
    - port: 8001
      targetPort: 8001